from PyQt5 import QtCore, QtGui, QtWidgets

####################################################################################################
import sqlite3  
from PyQt5.QtCore import Qt
from PyQt5.QtSql import QSqlTableModel
from PyQt5.QtWidgets import QApplication, QTableView
from PyQt5.QtSql import QSqlDatabase, QSqlQueryModel,QSqlQuery
from PyQt5.QtWidgets import QTableView
from PyQt5.QtGui import QStandardItemModel, QStandardItem
import subprocess
from PyQt5.QtWidgets import QMessageBox
####################################################################################################

class Ui_gestion(object):
    def setupUi(self, gestion):
        gestion.setObjectName("gestion")
        gestion.resize(1140, 523)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        gestion.setFont(font)
        gestion.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(gestion)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(370, 10, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 70, 1101, 401))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 20, 1051, 331))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 40, 55, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_title = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_title.setGeometry(QtCore.QRect(20, 70, 261, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lineEdit_title.setFont(font)
        self.lineEdit_title.setObjectName("lineEdit_title")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 110, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_author = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_author.setGeometry(QtCore.QRect(20, 140, 261, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lineEdit_author.setFont(font)
        self.lineEdit_author.setObjectName("lineEdit_author")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(20, 180, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_languge = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_languge.setGeometry(QtCore.QRect(20, 210, 261, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lineEdit_languge.setFont(font)
        self.lineEdit_languge.setObjectName("lineEdit_languge")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 250, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_edition = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_edition.setGeometry(QtCore.QRect(20, 280, 261, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lineEdit_edition.setFont(font)
        self.lineEdit_edition.setObjectName("lineEdit_edition")
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setGeometry(QtCore.QRect(310, 40, 41, 271))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(True)
        self.line.setFont(font)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(380, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_genre = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_genre.setGeometry(QtCore.QRect(380, 70, 651, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lineEdit_genre.setFont(font)
        self.lineEdit_genre.setObjectName("lineEdit_genre")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(380, 110, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEdit_nbp = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_nbp.setGeometry(QtCore.QRect(380, 140, 181, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lineEdit_nbp.setFont(font)
        self.lineEdit_nbp.setObjectName("lineEdit_nbp")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(380, 180, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lineEdit_rating = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_rating.setGeometry(QtCore.QRect(380, 210, 181, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lineEdit_rating.setFont(font)
        self.lineEdit_rating.setObjectName("lineEdit_rating")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(380, 250, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.lineEdit_bid = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_bid.setGeometry(QtCore.QRect(380, 280, 181, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lineEdit_bid.setFont(font)
        self.lineEdit_bid.setObjectName("lineEdit_bid")
        self.pushButton_save = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_save.setGeometry(QtCore.QRect(720, 200, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_showadd = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_showadd.setGeometry(QtCore.QRect(720, 257, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.pushButton_showadd.setFont(font)
        self.pushButton_showadd.setObjectName("pushButton_showadd")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 20, 1051, 331))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(380, 20, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.lineEdit_eid = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_eid.setGeometry(QtCore.QRect(422, 50, 131, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lineEdit_eid.setFont(font)
        self.lineEdit_eid.setObjectName("lineEdit_eid")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(50, 130, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.lineEdit_etitle = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_etitle.setGeometry(QtCore.QRect(130, 130, 161, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lineEdit_etitle.setFont(font)
        self.lineEdit_etitle.setObjectName("lineEdit_etitle")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(30, 170, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.lineEdit_eauthor = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_eauthor.setGeometry(QtCore.QRect(130, 170, 161, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lineEdit_eauthor.setFont(font)
        self.lineEdit_eauthor.setObjectName("lineEdit_eauthor")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(670, 130, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.lineEdit_elangugae = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_elangugae.setGeometry(QtCore.QRect(790, 130, 141, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lineEdit_elangugae.setFont(font)
        self.lineEdit_elangugae.setObjectName("lineEdit_elangugae")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(390, 170, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.lineEdit_eedition = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_eedition.setGeometry(QtCore.QRect(490, 170, 151, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lineEdit_eedition.setFont(font)
        self.lineEdit_eedition.setObjectName("lineEdit_eedition")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(310, 130, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.lineEdit_enbp = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_enbp.setGeometry(QtCore.QRect(490, 130, 151, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lineEdit_enbp.setFont(font)
        self.lineEdit_enbp.setObjectName("lineEdit_enbp")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(700, 170, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.lineEdit_erating = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_erating.setGeometry(QtCore.QRect(790, 170, 141, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lineEdit_erating.setFont(font)
        self.lineEdit_erating.setObjectName("lineEdit_erating")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(210, 210, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.lineEdit_egenre = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_egenre.setGeometry(QtCore.QRect(310, 210, 511, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lineEdit_egenre.setFont(font)
        self.lineEdit_egenre.setObjectName("lineEdit_egenre")
        self.line_2 = QtWidgets.QFrame(self.groupBox_3)
        self.line_2.setGeometry(QtCore.QRect(250, 80, 511, 20))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.pushButton_edit = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_edit.setGeometry(QtCore.QRect(230, 280, 291, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.pushButton_edit.setFont(font)
        self.pushButton_edit.setObjectName("pushButton_edit")
        self.pushButton_showedit = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_showedit.setGeometry(QtCore.QRect(550, 277, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.pushButton_showedit.setFont(font)
        self.pushButton_showedit.setObjectName("pushButton_showedit")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_4.setGeometry(QtCore.QRect(360, 40, 401, 231))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.lineEdit_dcid = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_dcid.setGeometry(QtCore.QRect(210, 110, 171, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lineEdit_dcid.setFont(font)
        self.lineEdit_dcid.setObjectName("lineEdit_dcid")
        self.pushButton_delete = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_delete.setGeometry(QtCore.QRect(110, 160, 161, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(10, 40, 391, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_21.setFont(font)
        self.label_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(100, 110, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.pushButto_showdelete = QtWidgets.QPushButton(self.tab_5)
        self.pushButto_showdelete.setGeometry(QtCore.QRect(300, 280, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButto_showdelete.setFont(font)
        self.pushButto_showdelete.setObjectName("pushButto_showdelete")
        self.tabWidget.addTab(self.tab_5, "")
        gestion.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(gestion)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1140, 26))
        self.menubar.setObjectName("menubar")
        gestion.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(gestion)
        self.statusbar.setObjectName("statusbar")
        gestion.setStatusBar(self.statusbar)

        self.retranslateUi(gestion)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(gestion)
#############################################################################################################
        self.pushButto_showdelete.clicked.connect(self.show_all)
        self.pushButton_showadd.clicked.connect(self.show_all)
        self.pushButton_showedit.clicked.connect(self.show_all)
        self.pushButton_save.clicked.connect(self.ADD)
        self.pushButton_edit.clicked.connect(self.edit)
        self.pushButton_delete.clicked.connect(self.delete)
#############################################################################################################

    def retranslateUi(self, gestion):
        _translate = QtCore.QCoreApplication.translate
        gestion.setWindowTitle(_translate("gestion", "MainWindow"))
        self.label.setText(_translate("gestion", "BOOK-STORE ARCHIVE"))
        self.groupBox_2.setTitle(_translate("gestion", "Add items menu :"))
        self.label_4.setText(_translate("gestion", "Title :"))
        self.label_5.setText(_translate("gestion", "Author : "))
        self.label_6.setText(_translate("gestion", "Language :"))
        self.label_7.setText(_translate("gestion", "Edition :"))
        self.label_8.setText(_translate("gestion", "Genre :"))
        self.label_9.setText(_translate("gestion", "Number of pages :"))
        self.label_10.setText(_translate("gestion", "Rating :"))
        self.label_11.setText(_translate("gestion", "Book ID :"))
        self.pushButton_save.setText(_translate("gestion", "SAVE"))
        self.pushButton_showadd.setText(_translate("gestion", "SHOW"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("gestion", "ADD"))
        self.groupBox_3.setTitle(_translate("gestion", "Editing Section :"))
        self.label_12.setText(_translate("gestion", "Book ID you want to edit : "))
        self.label_13.setText(_translate("gestion", "Title :"))
        self.label_14.setText(_translate("gestion", "Author :"))
        self.label_15.setText(_translate("gestion", "Language :"))
        self.label_16.setText(_translate("gestion", "Edition :"))
        self.label_17.setText(_translate("gestion", "Number of pages :"))
        self.label_18.setText(_translate("gestion", "Rating :"))
        self.label_19.setText(_translate("gestion", "Genre :"))
        self.pushButton_edit.setText(_translate("gestion", "EDIT"))
        self.pushButton_showedit.setText(_translate("gestion", "SHOW"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("gestion", "EDIT"))
        self.groupBox_4.setTitle(_translate("gestion", "delete settings :"))
        self.pushButton_delete.setText(_translate("gestion", "DELETE"))
        self.label_21.setText(_translate("gestion", "Enter the id or the Title of the book\n"
"you want to delete :"))
        self.label_20.setText(_translate("gestion", "BOOK ID :"))
        self.pushButto_showdelete.setText(_translate("gestion", "see the remaining data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("gestion", "DELETE"))

#############################################################################################################################################
    def show_all(self):
        gestion.close()
        subprocess.run(["python", "show_all_admin.py"])

    def ADD(self):
        Title = self.lineEdit_title.text()
        Author = self.lineEdit_author.text()
        Language = self.lineEdit_languge.text()
        Edition = self.lineEdit_edition.text()
        Genre = self.lineEdit_genre.text()
        NOP = self.lineEdit_nbp.text()
        Rating = self.lineEdit_rating.text()
        Book_id = self.lineEdit_bid.text()
        db = QSqlDatabase.addDatabase("QSQLITE")
        db.setDatabaseName("Books_Manga.sqlite")
        if not db.open():
            print("Error: could not open database")
            return False

        query = QSqlQuery()
        query.prepare("INSERT INTO books (B_ID,Title,Author,Language,Edition,Genre,NOP,Rating) VALUES (:B_ID,:Title,:Author,:Language,:Edition,:Genre,:NOP,:Rating)")
        query.bindValue(":B_ID", Book_id)
        query.bindValue(":Title", Title)
        query.bindValue(":Author", Author)
        query.bindValue(":Language", Language)
        query.bindValue(":Edition", Edition)
        query.bindValue(":Genre", Genre)
        query.bindValue(":NOP", NOP)
        query.bindValue(":Rating", Rating)
        if not query.exec_():
            print("Error:", query.lastError().text())
            return False
        else:
            self.lineEdit_title.clear()
            self.lineEdit_author.clear()
            self.lineEdit_languge.clear()
            self.lineEdit_edition.clear()
            self.lineEdit_genre.clear()
            self.lineEdit_nbp.clear()
            self.lineEdit_rating.clear()
            self.lineEdit_bid.clear()

            msg = QMessageBox()
            msg.setWindowTitle("Notification")
            msg.setText("the Book was added successfully")
            x = msg.exec_()
            db.close()

    def edit(self):

        Title = self.lineEdit_etitle.text()
        Author = self.lineEdit_eauthor.text()
        Language = self.lineEdit_elangugae.text()
        Edition = self.lineEdit_eedition.text()
        Genre = self.lineEdit_egenre.text()
        NOP = self.lineEdit_enbp.text()
        Rating = self.lineEdit_erating.text()
        Book_id = self.lineEdit_eid.text()

        # Connect to the database
        db = QSqlDatabase.addDatabase("QSQLITE")
        db.setDatabaseName("Books_Manga.sqlite")
        if not db.open():
            print("Could not open database")
            return False

        # Prepare the SQL update statement
        query = QSqlQuery()
        query.prepare("""
            UPDATE books
            SET Title=:title, Author=:author, Language=:language,
            Edition=:edition, Genre=:genre, NOP=:nop, Rating=:rating
            WHERE B_ID=:B_id
        """)
        query.bindValue(":title", Title)
        query.bindValue(":author", Author)
        query.bindValue(":language", Language)
        query.bindValue(":edition", Edition)
        query.bindValue(":genre", Genre)
        query.bindValue(":nop", NOP)
        query.bindValue(":rating", Rating)
        query.bindValue(":B_id", Book_id)

        # Execute the SQL update statement
        if not query.exec_():
            print("Error:", query.lastError().text())
            db.rollback()
            return False
        
        self.lineEdit_etitle.clear()
        self.lineEdit_eauthor.clear()
        self.lineEdit_elangugae.clear()
        self.lineEdit_eedition.clear()
        self.lineEdit_egenre.clear()
        self.lineEdit_enbp.clear()
        self.lineEdit_erating.clear()
        self.lineEdit_eid.clear()

        msg = QMessageBox()
        msg.setWindowTitle("Notification")
        msg.setText("the Book was edited successfully")
        x = msg.exec_()
        # Commit the changes to the database
        db.commit()
    
    
    def delete(self):
        Book_id = self.lineEdit_dcid.text()
        # Open the database
        db = QSqlDatabase.addDatabase("QSQLITE")
        db.setDatabaseName("Books_Manga.sqlite")
        if not db.open():
            print("Could not open database")

        # Execute the delete query
        query = QSqlQuery()
        query.prepare("DELETE FROM books WHERE B_ID = :b_id")
        query.bindValue(":b_id", Book_id)
        if not query.exec():
            print("Error deleting book:", query.lastError().text())
            return False
        
        self.lineEdit_dcid.clear()

        msg = QMessageBox()
        msg.setWindowTitle("Notification")
        msg.setText("the Book was deleted successfully")
        x = msg.exec_()
        # Commit the changes and close the database
        db.commit()
        db.close()

#############################################################################################################################################


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gestion = QtWidgets.QMainWindow()
    ui = Ui_gestion()
    ui.setupUi(gestion)
    gestion.show()
    app.exec_()

subprocess.run(["python", "login.py"])